### ISSUE TITLE
[Request] Add TCP Stealth system to protect unadvertised servers from port scanning

### ISSUE THREAD

**Issue by Megver83** [GrapheneOS-Archive/linux-hardened#62]
Please add support for [TCP Stealth](https://gnunet.org/kirsch2014knock). The original patches from the project are discontinued, but an independent kernel developer [continued its maintenance](https://git.hyperbola.info:50100/kernels/knock.git/tree/linux-libre).

However, as he develops a LTS distro (Hyperbola GNU/Linux-libre), I've encountered issues with this knock patches for mainline kernel (works good for LTS kernels, but doesn't compile for mainline).

I don't say that you have to continue maintaining these patches (although it's not a bad idea, they are awesome for hardened patches), but when he fixes them (someone could help [Emulatorman](https://www.hyperbola.info/members/developers/#Emulatorman), the maintainer, to get them working if you want) would be a good idea to add them in linux-hardened to improve security by protecting unadvertised servers from port scanning.

You can read more about this issue [here](https://www.fsf.org/news/gnu-hackers-unmask-massive-hacienda-surveillance-program-and-design-a-countermeasure) (it's an article from 2014 however, but it applies for nowadays anyways).

**Comment by thestinger** [comment]
I think it makes more sense to only expose SSH with every other service tunnelled over it. It should be built against OpenSSH which is used across operating systems rather than patching the kernel for each operating system by inventing another form of authentication. I don't really like the approach and I don't think it's much good beyond a proof of concept.

I'm not willing to carry patches like downstream even if the approach made more sense to me. It's not really within the scope of the project which is going to be kernel self-protection. There are currently some changes outside of that scope but they're going to be landed upstream (ASLR improvements) or dropped (features overlapping with SELinux or other existing options) when there's some more time to pick up development again.
